builds:
  - env:
      - CGO_ENABLED=0
    binary:
      got_random
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - replacements:
      386: i386
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip

    name_template: "got_random_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - none*


checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - got_random
    image_templates:
      - "yarlson/gotrandomcharacter:latest"
      - "yarlson/gotrandomcharacter:{{ .Tag }}"
    skip_push: true
    dockerfile: Dockerfile
